// src/components/Header/Header.svelte
<script lang="ts">
	import clsx from 'clsx';

	import { Github, Discord } from ':icons';
	import { DISCORD_INVITE_URL, PROJECT_URL } from ':config';

	import Search from './Search.svelte';

	const linkClasses = "rounded-lg transition-colors hocus:text-textPrimary hocus:bg-bgSecondary"
</script>

<header class="h-16 w-full shadow-lg py-2 px-2 bg-bgPrimary text-textSecondary">
	<div class="container mx-auto h-full flex items-center justify-between">
		<div class="flex">
			<a
				href="#main-content"
				class={clsx(linkClasses, "sr-only focus:not-sr-only underline focus:py-2 focus:px-4")}
			>
				Skip to content
			</a>
			<a class="" href="/">LOGO Thyseus</a>
		</div>
		<div class="flex items-center gap-4">
			<nav class="block h-full">
				<ul class="flex items-center gap-1">
					{@render navLink('Docs', '/docs')}
					{@render navLink('Blog', '/blog')}
				</ul>
			</nav>
			<Search />
			<div class="flex items-center gap-1">
				{@render iconLink(Github, 'Github', PROJECT_URL)}
				{@render iconLink(Discord, 'Discord', DISCORD_INVITE_URL)}
			</div>
		</div>
	</div>
</header>

{#snippet navLink(name: string, href: string)}
	<li>
		<a
			{href}
			class={clsx(linkClasses, 'px-2 py-2 text-xs font-semibold uppercase tracking-wider')}
		>
			{name}
		</a>
	</li>
{/snippet}
{#snippet iconLink(Icon: any, name: string, href: string)}
<a {href} class={clsx(linkClasses, 'px-2 py-2')}>
	<Icon />
	<span class="sr-only">{name}</span>
</a>
{/snippet}

// src/components/Home/Header.tsx
import Link from 'next/link';
import { Search } from '../Header/Search/Search';
import { Logo } from ':ui';
import { useThemeConfig } from '../ThemeConfig';
import { useHasScrolled } from './useHasScrolled';
import clsx from 'clsx';

export function Header() {
	const { projectRepository } = useThemeConfig();
	const hasScrolled = useHasScrolled();
	return (
		<header
			className={clsx(
				'h-16 flex-shrink-0 flex items-center justify-between px-6 py-1 gap-4 shadow-lg fixed w-full transition-all',
				hasScrolled &&
					'backdrop-blur-sm from-black/60 to-black/20 bg-gradient-to-b',
			)}
		>
			<div className="h-full flex-1">
				<Link href="/" className="overflow-hidden">
					<Logo className="h-full" aria-hidden />
					<span className="sr-only">Thyseus</span>
				</Link>
			</div>

			<nav>
				<ul className="flex text-sm gap-4">
					<li>
						<Link
							className="px-4 py-2 text-xs font-medium uppercase tracking-wide transition-all hover:tracking-widest"
							href="/blog"
						>
							Blog
						</Link>
					</li>
					<li>
						<Link
							className="px-4 py-2 text-xs font-medium uppercase tracking-wider"
							href="/docs"
						>
							Docs
						</Link>
					</li>
				</ul>
			</nav>
			<Search />
			<a
				className="hover:text-gray-300 focus:text-gray-300 p-1.5"
				href={projectRepository}
			>
				<svg
					width="24"
					height="24"
					fill="currentColor"
					viewBox="3 3 18 18"
				>
					<path d="M12 3C7.0275 3 3 7.12937 3 12.2276C3 16.3109 5.57625 19.7597 9.15374 20.9824C9.60374 21.0631 9.77249 20.7863 9.77249 20.5441C9.77249 20.3249 9.76125 19.5982 9.76125 18.8254C7.5 19.2522 6.915 18.2602 6.735 17.7412C6.63375 17.4759 6.19499 16.6569 5.8125 16.4378C5.4975 16.2647 5.0475 15.838 5.80124 15.8264C6.51 15.8149 7.01625 16.4954 7.18499 16.7723C7.99499 18.1679 9.28875 17.7758 9.80625 17.5335C9.885 16.9337 10.1212 16.53 10.38 16.2993C8.3775 16.0687 6.285 15.2728 6.285 11.7432C6.285 10.7397 6.63375 9.9092 7.20749 9.26326C7.1175 9.03257 6.8025 8.08674 7.2975 6.81794C7.2975 6.81794 8.05125 6.57571 9.77249 7.76377C10.4925 7.55615 11.2575 7.45234 12.0225 7.45234C12.7875 7.45234 13.5525 7.55615 14.2725 7.76377C15.9937 6.56418 16.7475 6.81794 16.7475 6.81794C17.2424 8.08674 16.9275 9.03257 16.8375 9.26326C17.4113 9.9092 17.76 10.7281 17.76 11.7432C17.76 15.2843 15.6563 16.0687 13.6537 16.2993C13.98 16.5877 14.2613 17.1414 14.2613 18.0065C14.2613 19.2407 14.25 20.2326 14.25 20.5441C14.25 20.7863 14.4188 21.0746 14.8688 20.9824C16.6554 20.364 18.2079 19.1866 19.3078 17.6162C20.4077 16.0457 20.9995 14.1611 21 12.2276C21 7.12937 16.9725 3 12 3Z"></path>
				</svg>
				<span className="sr-only">GitHub</span>
			</a>
		</header>
	);
}
